"""a=5
b=10
c=a-b
print(c)"""
a=5
b=10
print('addition:',a+b)
print('subtraction:',a-b)
print('multiplication:',a*b)
print("exponent:",a**b)
print("divion:",a/b)
print("floor_division:",a//b)
print("modulus:",a%b)